[package]
name = "sequel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sequel-client"
path = "src/bin/client.rs"

[[bin]]
name = "sequel-server"
path = "src/bin/server.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
phf = { version = "0.10", features = ["macros"] }
